// Generated by CoffeeScript 1.7.1
var Bar, Foo, myBar, myFoo;

Foo = (function() {
  function Foo() {}

  return Foo;

})();

Bar = (function() {
  function Bar() {}

  return Bar;

})();

myFoo = new Foo();

myBar = new Bar();

//# sourceMappingURL=inputTest.map
